export const statesData = [
  { state: 'Alabama', abbr: 'AL', slug: 'alabama', count: 45 },
  { state: 'Alaska', abbr: 'AK', slug: 'alaska', count: 12 },
  { state: 'Arizona', abbr: 'AZ', slug: 'arizona', count: 98 },
  { state: 'Arkansas', abbr: 'AR', slug: 'arkansas', count: 32 },
  { state: 'California', abbr: 'CA', slug: 'california', count: 450 },
  { state: 'Colorado', abbr: 'CO', slug: 'colorado', count: 87 },
  { state: 'Connecticut', abbr: 'CT', slug: 'connecticut', count: 65 },
  { state: 'Delaware', abbr: 'DE', slug: 'delaware', count: 18 },
  { state: 'Florida', abbr: 'FL', slug: 'florida', count: 320 },
  { state: 'Georgia', abbr: 'GA', slug: 'georgia', count: 110 },
  { state: 'Hawaii', abbr: 'HI', slug: 'hawaii', count: 28 },
  { state: 'Idaho', abbr: 'ID', slug: 'idaho', count: 24 },
  { state: 'Illinois', abbr: 'IL', slug: 'illinois', count: 180 },
  { state: 'Indiana', abbr: 'IN', slug: 'indiana', count: 72 },
  { state: 'Iowa', abbr: 'IA', slug: 'iowa', count: 38 },
  { state: 'Kansas', abbr: 'KS', slug: 'kansas', count: 42 },
  { state: 'Kentucky', abbr: 'KY', slug: 'kentucky', count: 48 },
  { state: 'Louisiana', abbr: 'LA', slug: 'louisiana', count: 55 },
  { state: 'Maine', abbr: 'ME', slug: 'maine', count: 22 },
  { state: 'Maryland', abbr: 'MD', slug: 'maryland', count: 85 },
  { state: 'Massachusetts', abbr: 'MA', slug: 'massachusetts', count: 120 },
  { state: 'Michigan', abbr: 'MI', slug: 'michigan', count: 105 },
  { state: 'Minnesota', abbr: 'MN', slug: 'minnesota', count: 68 },
  { state: 'Mississippi', abbr: 'MS', slug: 'mississippi', count: 28 },
  { state: 'Missouri', abbr: 'MO', slug: 'missouri', count: 62 },
  { state: 'Montana', abbr: 'MT', slug: 'montana', count: 18 },
  { state: 'Nebraska', abbr: 'NE', slug: 'nebraska', count: 25 },
  { state: 'Nevada', abbr: 'NV', slug: 'nevada', count: 75 },
  { state: 'New Hampshire', abbr: 'NH', slug: 'new-hampshire', count: 30 },
  { state: 'New Jersey', abbr: 'NJ', slug: 'new-jersey', count: 145 },
  { state: 'New Mexico', abbr: 'NM', slug: 'new-mexico', count: 35 },
  { state: 'New York', abbr: 'NY', slug: 'new-york', count: 290 },
  { state: 'North Carolina', abbr: 'NC', slug: 'north-carolina', count: 95 },
  { state: 'North Dakota', abbr: 'ND', slug: 'north-dakota', count: 12 },
  { state: 'Ohio', abbr: 'OH', slug: 'ohio', count: 115 },
  { state: 'Oklahoma', abbr: 'OK', slug: 'oklahoma', count: 45 },
  { state: 'Oregon', abbr: 'OR', slug: 'oregon', count: 58 },
  { state: 'Pennsylvania', abbr: 'PA', slug: 'pennsylvania', count: 160 },
  { state: 'Rhode Island', abbr: 'RI', slug: 'rhode-island', count: 20 },
  { state: 'South Carolina', abbr: 'SC', slug: 'south-carolina', count: 52 },
  { state: 'South Dakota', abbr: 'SD', slug: 'south-dakota', count: 15 },
  { state: 'Tennessee', abbr: 'TN', slug: 'tennessee', count: 70 },
  { state: 'Texas', abbr: 'TX', slug: 'texas', count: 380 },
  { state: 'Utah', abbr: 'UT', slug: 'utah', count: 45 },
  { state: 'Vermont', abbr: 'VT', slug: 'vermont', count: 16 },
  { state: 'Virginia', abbr: 'VA', slug: 'virginia', count: 88 },
  { state: 'Washington', abbr: 'WA', slug: 'washington', count: 92 },
  { state: 'West Virginia', abbr: 'WV', slug: 'west-virginia', count: 22 },
  { state: 'Wisconsin', abbr: 'WI', slug: 'wisconsin', count: 60 },
  { state: 'Wyoming', abbr: 'WY', slug: 'wyoming', count: 10 },
]

export const mockGyms = [
  {
    id: '1',
    name: 'Elite Boxing Gym',
    full_address: '123 Main St, Los Angeles, CA 90001',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90001',
    phone_number: '(555) 123-4567',
    site: 'https://example.com',
    source_url: 'https://maps.google.com',
    review_stars: 4.5,
    review_count: 128,
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: '2',
    name: 'Champions Boxing Club',
    full_address: '456 Oak Ave, Brooklyn, NY 11201',
    city: 'Brooklyn',
    state: 'NY',
    postal_code: '11201',
    phone_number: '(555) 234-5678',
    site: 'https://example.com',
    source_url: 'https://maps.google.com',
    review_stars: 4.8,
    review_count: 89,
    latitude: 40.6782,
    longitude: -73.9442,
  },
  {
    id: '3',
    name: 'Fighter\'s Paradise',
    full_address: '789 Elm St, Houston, TX 77001',
    city: 'Houston',
    state: 'TX',
    postal_code: '77001',
    phone_number: '(555) 345-6789',
    site: 'https://example.com',
    source_url: 'https://maps.google.com',
    review_stars: 4.3,
    review_count: 67,
    latitude: 29.7604,
    longitude: -95.3698,
  },
]

export const citiesByState: Record<string, Array<{ name: string; slug: string; count: number }>> = {
  'california': [
    { name: 'Los Angeles', slug: 'los-angeles', count: 85 },
    { name: 'San Francisco', slug: 'san-francisco', count: 45 },
    { name: 'San Diego', slug: 'san-diego', count: 38 },
    { name: 'Sacramento', slug: 'sacramento', count: 22 },
    { name: 'San Jose', slug: 'san-jose', count: 28 },
  ],
  'texas': [
    { name: 'Houston', slug: 'houston', count: 65 },
    { name: 'Dallas', slug: 'dallas', count: 52 },
    { name: 'Austin', slug: 'austin', count: 38 },
    { name: 'San Antonio', slug: 'san-antonio', count: 35 },
    { name: 'Fort Worth', slug: 'fort-worth', count: 28 },
  ],
  'new-york': [
    { name: 'New York', slug: 'new-york', count: 125 },
    { name: 'Brooklyn', slug: 'brooklyn', count: 45 },
    { name: 'Buffalo', slug: 'buffalo', count: 18 },
    { name: 'Rochester', slug: 'rochester', count: 15 },
    { name: 'Albany', slug: 'albany', count: 12 },
  ],
  'massachusetts': [
    { name: 'Boston', slug: 'boston', count: 45 },
    { name: 'Worcester', slug: 'worcester', count: 12 },
    { name: 'Springfield', slug: 'springfield', count: 8 },
    { name: 'Cambridge', slug: 'cambridge', count: 15 },
    { name: 'Lowell', slug: 'lowell', count: 6 },
  ],
}