export const statesData = [
  { state: 'Alabama', slug: 'alabama', count: 45 },
  { state: 'Alaska', slug: 'alaska', count: 12 },
  { state: 'Arizona', slug: 'arizona', count: 98 },
  { state: 'Arkansas', slug: 'arkansas', count: 32 },
  { state: 'California', slug: 'california', count: 450 },
  { state: 'Colorado', slug: 'colorado', count: 87 },
  { state: 'Connecticut', slug: 'connecticut', count: 65 },
  { state: 'Delaware', slug: 'delaware', count: 18 },
  { state: 'Florida', slug: 'florida', count: 320 },
  { state: 'Georgia', slug: 'georgia', count: 110 },
  { state: 'Hawaii', slug: 'hawaii', count: 28 },
  { state: 'Idaho', slug: 'idaho', count: 24 },
  { state: 'Illinois', slug: 'illinois', count: 180 },
  { state: 'Indiana', slug: 'indiana', count: 72 },
  { state: 'Iowa', slug: 'iowa', count: 38 },
  { state: 'Kansas', slug: 'kansas', count: 42 },
  { state: 'Kentucky', slug: 'kentucky', count: 48 },
  { state: 'Louisiana', slug: 'louisiana', count: 55 },
  { state: 'Maine', slug: 'maine', count: 22 },
  { state: 'Maryland', slug: 'maryland', count: 85 },
  { state: 'Massachusetts', slug: 'massachusetts', count: 120 },
  { state: 'Michigan', slug: 'michigan', count: 105 },
  { state: 'Minnesota', slug: 'minnesota', count: 68 },
  { state: 'Mississippi', slug: 'mississippi', count: 28 },
  { state: 'Missouri', slug: 'missouri', count: 62 },
  { state: 'Montana', slug: 'montana', count: 18 },
  { state: 'Nebraska', slug: 'nebraska', count: 25 },
  { state: 'Nevada', slug: 'nevada', count: 75 },
  { state: 'New Hampshire', slug: 'new-hampshire', count: 30 },
  { state: 'New Jersey', slug: 'new-jersey', count: 145 },
  { state: 'New Mexico', slug: 'new-mexico', count: 35 },
  { state: 'New York', slug: 'new-york', count: 290 },
  { state: 'North Carolina', slug: 'north-carolina', count: 95 },
  { state: 'North Dakota', slug: 'north-dakota', count: 12 },
  { state: 'Ohio', slug: 'ohio', count: 115 },
  { state: 'Oklahoma', slug: 'oklahoma', count: 45 },
  { state: 'Oregon', slug: 'oregon', count: 58 },
  { state: 'Pennsylvania', slug: 'pennsylvania', count: 160 },
  { state: 'Rhode Island', slug: 'rhode-island', count: 20 },
  { state: 'South Carolina', slug: 'south-carolina', count: 52 },
  { state: 'South Dakota', slug: 'south-dakota', count: 15 },
  { state: 'Tennessee', slug: 'tennessee', count: 70 },
  { state: 'Texas', slug: 'texas', count: 380 },
  { state: 'Utah', slug: 'utah', count: 45 },
  { state: 'Vermont', slug: 'vermont', count: 16 },
  { state: 'Virginia', slug: 'virginia', count: 88 },
  { state: 'Washington', slug: 'washington', count: 92 },
  { state: 'West Virginia', slug: 'west-virginia', count: 22 },
  { state: 'Wisconsin', slug: 'wisconsin', count: 60 },
  { state: 'Wyoming', slug: 'wyoming', count: 10 },
]

export const mockGyms = [
  {
    id: '1',
    name: 'Elite Boxing Gym',
    full_address: '123 Main St, Los Angeles, CA 90001',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90001',
    phone_number: '(555) 123-4567',
    site: 'https://example.com',
    source_url: 'https://maps.google.com',
    review_stars: 4.5,
    review_count: 128,
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: '2',
    name: 'Champions Boxing Club',
    full_address: '456 Oak Ave, Brooklyn, NY 11201',
    city: 'Brooklyn',
    state: 'NY',
    postal_code: '11201',
    phone_number: '(555) 234-5678',
    site: 'https://example.com',
    source_url: 'https://maps.google.com',
    review_stars: 4.8,
    review_count: 89,
    latitude: 40.6782,
    longitude: -73.9442,
  },
  {
    id: '3',
    name: 'Fighter\'s Paradise',
    full_address: '789 Elm St, Houston, TX 77001',
    city: 'Houston',
    state: 'TX',
    postal_code: '77001',
    phone_number: '(555) 345-6789',
    site: 'https://example.com',
    source_url: 'https://maps.google.com',
    review_stars: 4.3,
    review_count: 67,
    latitude: 29.7604,
    longitude: -95.3698,
  },
]

export const citiesByState: Record<string, Array<{ name: string; slug: string; count: number }>> = {
  'california': [
    { name: 'Los Angeles', slug: 'los-angeles', count: 85 },
    { name: 'San Francisco', slug: 'san-francisco', count: 45 },
    { name: 'San Diego', slug: 'san-diego', count: 38 },
    { name: 'Sacramento', slug: 'sacramento', count: 22 },
    { name: 'San Jose', slug: 'san-jose', count: 28 },
  ],
  'texas': [
    { name: 'Houston', slug: 'houston', count: 65 },
    { name: 'Dallas', slug: 'dallas', count: 52 },
    { name: 'Austin', slug: 'austin', count: 38 },
    { name: 'San Antonio', slug: 'san-antonio', count: 35 },
    { name: 'Fort Worth', slug: 'fort-worth', count: 28 },
  ],
  'new-york': [
    { name: 'New York', slug: 'new-york', count: 125 },
    { name: 'Brooklyn', slug: 'brooklyn', count: 45 },
    { name: 'Buffalo', slug: 'buffalo', count: 18 },
    { name: 'Rochester', slug: 'rochester', count: 15 },
    { name: 'Albany', slug: 'albany', count: 12 },
  ],
}